# Generated by Django 5.0.2 on 2025-10-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attribute_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Define attribute fields for products in this category'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific attributes like size, spicy level, wear type, etc.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_one_time',
            field=models.BooleanField(default=False, help_text="One-time items are hidden when out of stock. Restockable items show 'Out of Stock'."),
        ),
    ]
