# Generated by Django 5.0.2 on 2025-10-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_attribute_schema_product_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for subcategories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_restockable',
            field=models.BooleanField(default=True, help_text='Can this item be restocked? Alternative to is_one_time.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='svg_placeholder',
            field=models.TextField(blank=True, default='', help_text='SVG code for placeholder image'),
        ),
    ]
